import { Injectable } from '@nestjs/common';
import { RenderContext } from '../models/readme.model';
import {
  DynamicProvider,
  ProviderCapability,
  ProviderMetadata,
  ProviderRequest,
  ProviderResult,
  ProviderHealth,
} from './provider.contract';
import { ProviderUrlBuilder } from './provider-url.builder';

// ---------------------------------------------------------------------------
// 1. External GitHub Stats Card Provider (github-readme-stats)
// ---------------------------------------------------------------------------

@Injectable()
export class ExternalGithubStatsProvider implements DynamicProvider {
  private readonly baseUrl =
    'https://github-readme-stats.vercel.app/api?username={username}&show_icons={showIcons}&theme={theme}';
  private readonly allowedHosts = ['github-readme-stats.vercel.app'];

  metadata(): ProviderMetadata {
    return {
      providerKey: 'github-stats-readme',
      name: 'GitHub Readme Stats Card',
      description: 'Dynamic statistics image card generated by github-readme-stats.',
      category: 'GITHUB_STATS',
      version: '1.0.0',
      enabled: true,
      status: 'ENABLED',
      isSystem: true,
      capabilities: ['DYNAMIC_IMAGE', 'STATISTICS'],
      supportedComponents: ['github-stats'],
      documentationUrl: 'https://github.com/anuraghazra/github-readme-stats',
      configurationSchema: [
        { name: 'username', type: 'username', required: true, description: 'GitHub username' },
        {
          name: 'theme',
          type: 'enum',
          required: false,
          default: 'default',
          enumValues: [
            'default',
            'dark',
            'radical',
            'merko',
            'gruvbox',
            'tokyonight',
            'onedark',
            'cobalt',
            'synthwave',
            'highcontrast',
            'dracula',
          ],
          description: 'Color theme of the statistics card',
        },
        {
          name: 'showIcons',
          type: 'boolean',
          required: false,
          default: true,
          description: 'Show icon graphics for each metric',
        },
      ],
    };
  }

  capabilities(): ProviderCapability[] {
    return ['DYNAMIC_IMAGE', 'STATISTICS'];
  }

  validateConfiguration(parameters: Record<string, unknown>): Record<string, unknown> {
    return ProviderUrlBuilder.validateParameters(
      'github-stats-readme',
      this.metadata().configurationSchema,
      parameters,
    );
  }

  resolve(request: ProviderRequest, context?: RenderContext): ProviderResult {
    // SECURITY: username is bound to the authenticated render context. Any
    // caller-supplied value in request.parameters is ignored on purpose to
    // prevent impersonation of arbitrary GitHub users in published READMEs.
    const username = context?.profile?.githubLogin;
    if (!username) {
      return {
        providerKey: 'github-stats-readme',
        version: '1.0.0',
        status: 'UNAVAILABLE',
        contentType: 'IMAGE_URL',
        warnings: ['Authenticated GitHub username unavailable in render context'],
        generatedAt: new Date().toISOString(),
      };
    }
    const { username: _ignored, ...safeParams } = request.parameters as Record<string, unknown>;
    const rawParams = { ...safeParams, username };

    const validated = this.validateConfiguration(rawParams) as Record<string, string>;
    const url = ProviderUrlBuilder.buildUrl('github-stats-readme', this.baseUrl, validated);
    ProviderUrlBuilder.assertUrlSafety('github-stats-readme', url, this.allowedHosts);

    return {
      providerKey: 'github-stats-readme',
      version: '1.0.0',
      status: 'SUCCESS',
      contentType: 'IMAGE_URL',
      url,
      metadata: {
        host: 'github-readme-stats.vercel.app',
        theme: validated['theme'] || 'default',
      },
      generatedAt: new Date().toISOString(),
    };
  }

  health(): ProviderHealth {
    return {
      providerKey: 'github-stats-readme',
      status: 'ENABLED',
      lastCheckedAt: new Date().toISOString(),
      lastSuccessAt: new Date().toISOString(),
      failureCount: 0,
      latencyMs: 45,
    };
  }
}

// ---------------------------------------------------------------------------
// 2. External GitHub Streak Stats Provider (demolab streak-stats)
// ---------------------------------------------------------------------------

@Injectable()
export class ExternalStreakStatsProvider implements DynamicProvider {
  private readonly baseUrl = 'https://streak-stats.demolab.com?user={username}&theme={theme}';
  private readonly allowedHosts = ['streak-stats.demolab.com'];

  metadata(): ProviderMetadata {
    return {
      providerKey: 'github-streak-stats',
      name: 'GitHub Streak Stats Card',
      description: 'Dynamic streak statistics card displaying consecutive contribution days.',
      category: 'STREAK',
      version: '1.0.0',
      enabled: true,
      status: 'ENABLED',
      isSystem: true,
      capabilities: ['DYNAMIC_IMAGE', 'STATISTICS'],
      supportedComponents: ['streak-stats'],
      documentationUrl: 'https://github.com/DenverCoder1/github-readme-streak-stats',
      configurationSchema: [
        { name: 'username', type: 'username', required: true, description: 'GitHub username' },
        {
          name: 'theme',
          type: 'enum',
          required: false,
          default: 'default',
          enumValues: ['default', 'dark', 'highcontrast', 'tokyonight', 'radical'],
          description: 'Card color theme',
        },
      ],
    };
  }

  capabilities(): ProviderCapability[] {
    return ['DYNAMIC_IMAGE', 'STATISTICS'];
  }

  validateConfiguration(parameters: Record<string, unknown>): Record<string, unknown> {
    return ProviderUrlBuilder.validateParameters(
      'github-streak-stats',
      this.metadata().configurationSchema,
      parameters,
    );
  }

  resolve(request: ProviderRequest, context?: RenderContext): ProviderResult {
    // SECURITY: username is bound to the authenticated render context. Caller-
    // supplied values are ignored to prevent impersonation of arbitrary users.
    const username = context?.profile?.githubLogin;
    if (!username) {
      return {
        providerKey: 'github-streak-stats',
        version: '1.0.0',
        status: 'UNAVAILABLE',
        contentType: 'IMAGE_URL',
        warnings: ['Authenticated GitHub username unavailable in render context'],
        generatedAt: new Date().toISOString(),
      };
    }
    const { username: _ignored, ...safeParams } = request.parameters as Record<string, unknown>;
    const rawParams = { ...safeParams, username };

    const validated = this.validateConfiguration(rawParams) as Record<string, string>;
    const url = ProviderUrlBuilder.buildUrl('github-streak-stats', this.baseUrl, validated);
    ProviderUrlBuilder.assertUrlSafety('github-streak-stats', url, this.allowedHosts);

    return {
      providerKey: 'github-streak-stats',
      version: '1.0.0',
      status: 'SUCCESS',
      contentType: 'IMAGE_URL',
      url,
      metadata: {
        host: 'streak-stats.demolab.com',
        theme: validated['theme'] || 'default',
      },
      generatedAt: new Date().toISOString(),
    };
  }

  health(): ProviderHealth {
    return {
      providerKey: 'github-streak-stats',
      status: 'ENABLED',
      lastCheckedAt: new Date().toISOString(),
      lastSuccessAt: new Date().toISOString(),
      failureCount: 0,
      latencyMs: 38,
    };
  }
}

// ---------------------------------------------------------------------------
// 3. External Top Languages Provider (github-readme-stats top-langs)
// ---------------------------------------------------------------------------

@Injectable()
export class ExternalTopLanguagesProvider implements DynamicProvider {
  private readonly baseUrl =
    'https://github-readme-stats.vercel.app/api/top-langs/?username={username}&layout={layout}&theme={theme}';
  private readonly allowedHosts = ['github-readme-stats.vercel.app'];

  metadata(): ProviderMetadata {
    return {
      providerKey: 'github-top-langs',
      name: 'GitHub Top Languages Card',
      description: 'Dynamic visual breakdown of most used languages across public repos.',
      category: 'TOP_LANGUAGES',
      version: '1.0.0',
      enabled: true,
      status: 'ENABLED',
      isSystem: true,
      capabilities: ['DYNAMIC_IMAGE', 'STATISTICS'],
      supportedComponents: ['top-languages'],
      documentationUrl: 'https://github.com/anuraghazra/github-readme-stats',
      configurationSchema: [
        { name: 'username', type: 'username', required: true, description: 'GitHub username' },
        {
          name: 'layout',
          type: 'enum',
          required: false,
          default: 'compact',
          enumValues: ['compact', 'normal', 'donut', 'donut-vertical', 'pie'],
          description: 'Visual layout design',
        },
        {
          name: 'theme',
          type: 'enum',
          required: false,
          default: 'default',
          enumValues: ['default', 'dark', 'radical', 'tokyonight', 'dracula'],
          description: 'Color theme',
        },
      ],
    };
  }

  capabilities(): ProviderCapability[] {
    return ['DYNAMIC_IMAGE', 'STATISTICS'];
  }

  validateConfiguration(parameters: Record<string, unknown>): Record<string, unknown> {
    return ProviderUrlBuilder.validateParameters(
      'github-top-langs',
      this.metadata().configurationSchema,
      parameters,
    );
  }

  resolve(request: ProviderRequest, context?: RenderContext): ProviderResult {
    // SECURITY: username is bound to the authenticated render context. Caller-
    // supplied values are ignored to prevent impersonation of arbitrary users.
    const username = context?.profile?.githubLogin;
    if (!username) {
      return {
        providerKey: 'github-top-langs',
        version: '1.0.0',
        status: 'UNAVAILABLE',
        contentType: 'IMAGE_URL',
        warnings: ['Authenticated GitHub username unavailable in render context'],
        generatedAt: new Date().toISOString(),
      };
    }
    const { username: _ignored, ...safeParams } = request.parameters as Record<string, unknown>;
    const rawParams = { ...safeParams, username };

    const validated = this.validateConfiguration(rawParams) as Record<string, string>;
    const url = ProviderUrlBuilder.buildUrl('github-top-langs', this.baseUrl, validated);
    ProviderUrlBuilder.assertUrlSafety('github-top-langs', url, this.allowedHosts);

    return {
      providerKey: 'github-top-langs',
      version: '1.0.0',
      status: 'SUCCESS',
      contentType: 'IMAGE_URL',
      url,
      metadata: {
        host: 'github-readme-stats.vercel.app',
        layout: validated['layout'] || 'compact',
      },
      generatedAt: new Date().toISOString(),
    };
  }

  health(): ProviderHealth {
    return {
      providerKey: 'github-top-langs',
      status: 'ENABLED',
      lastCheckedAt: new Date().toISOString(),
      lastSuccessAt: new Date().toISOString(),
      failureCount: 0,
      latencyMs: 52,
    };
  }
}

// ---------------------------------------------------------------------------
// 4. External Profile Trophy Provider (github-profile-trophy)
// ---------------------------------------------------------------------------

@Injectable()
export class ExternalProfileTrophyProvider implements DynamicProvider {
  private readonly baseUrl =
    'https://github-profile-trophy.vercel.app/?username={username}&theme={theme}&no-frame={noFrame}';
  private readonly allowedHosts = ['github-profile-trophy.vercel.app'];

  metadata(): ProviderMetadata {
    return {
      providerKey: 'github-profile-trophy',
      name: 'GitHub Profile Trophy Wall',
      description: 'Dynamic trophy visual showcase generated from GitHub achievements.',
      category: 'TROPHIES',
      version: '1.0.0',
      enabled: true,
      status: 'ENABLED',
      isSystem: true,
      capabilities: ['DYNAMIC_IMAGE', 'TROPHY'],
      supportedComponents: ['trophy-wall'],
      documentationUrl: 'https://github.com/ryo-ma/github-profile-trophy',
      configurationSchema: [
        { name: 'username', type: 'username', required: true, description: 'GitHub username' },
        {
          name: 'theme',
          type: 'enum',
          required: false,
          default: 'default',
          enumValues: ['default', 'dark', 'radical', 'tokyonight', 'dracula', 'flat'],
          description: 'Color theme',
        },
        {
          name: 'noFrame',
          type: 'boolean',
          required: false,
          default: false,
          description: 'Render without decorative border frames',
        },
      ],
    };
  }

  capabilities(): ProviderCapability[] {
    return ['DYNAMIC_IMAGE', 'TROPHY'];
  }

  validateConfiguration(parameters: Record<string, unknown>): Record<string, unknown> {
    return ProviderUrlBuilder.validateParameters(
      'github-profile-trophy',
      this.metadata().configurationSchema,
      parameters,
    );
  }

  resolve(request: ProviderRequest, context?: RenderContext): ProviderResult {
    // SECURITY: username is bound to the authenticated render context. Caller-
    // supplied values are ignored to prevent impersonation of arbitrary users.
    const username = context?.profile?.githubLogin;
    if (!username) {
      return {
        providerKey: 'github-profile-trophy',
        version: '1.0.0',
        status: 'UNAVAILABLE',
        contentType: 'IMAGE_URL',
        warnings: ['Authenticated GitHub username unavailable in render context'],
        generatedAt: new Date().toISOString(),
      };
    }
    const { username: _ignored, ...safeParams } = request.parameters as Record<string, unknown>;
    const rawParams = { ...safeParams, username };

    const validated = this.validateConfiguration(rawParams) as Record<string, string>;
    const url = ProviderUrlBuilder.buildUrl('github-profile-trophy', this.baseUrl, validated);
    ProviderUrlBuilder.assertUrlSafety('github-profile-trophy', url, this.allowedHosts);

    return {
      providerKey: 'github-profile-trophy',
      version: '1.0.0',
      status: 'SUCCESS',
      contentType: 'IMAGE_URL',
      url,
      metadata: {
        host: 'github-profile-trophy.vercel.app',
      },
      generatedAt: new Date().toISOString(),
    };
  }

  health(): ProviderHealth {
    return {
      providerKey: 'github-profile-trophy',
      status: 'ENABLED',
      lastCheckedAt: new Date().toISOString(),
      lastSuccessAt: new Date().toISOString(),
      failureCount: 0,
      latencyMs: 60,
    };
  }
}

// ---------------------------------------------------------------------------
// 5. External Shields.io Badge Provider
// ---------------------------------------------------------------------------

@Injectable()
export class ExternalShieldsBadgeProvider implements DynamicProvider {
  private readonly baseUrl = 'https://img.shields.io/badge/{label}-{message}-{color}?style={style}';
  private readonly allowedHosts = ['img.shields.io'];

  metadata(): ProviderMetadata {
    return {
      providerKey: 'shields-badge',
      name: 'Shields.io Badge Provider',
      description: 'Generates concise SVG badge images with custom labels, messages, and colors.',
      category: 'BADGES',
      version: '1.0.0',
      enabled: true,
      status: 'ENABLED',
      isSystem: true,
      capabilities: ['DYNAMIC_IMAGE', 'BADGE'],
      supportedComponents: ['skills', 'callout'],
      documentationUrl: 'https://shields.io',
      configurationSchema: [
        {
          name: 'label',
          type: 'string',
          required: true,
          maxLength: 64,
          pattern: '^[A-Za-z0-9 _.\\-%+=]+$',
          description: 'Left badge label',
        },
        {
          name: 'message',
          type: 'string',
          required: true,
          maxLength: 64,
          pattern: '^[A-Za-z0-9 _.\\-%+=]+$',
          description: 'Right badge text',
        },
        {
          name: 'color',
          type: 'enum',
          required: true,
          enumValues: [
            'blue',
            'brightgreen',
            'green',
            'yellow',
            'orange',
            'red',
            'lightgrey',
            'blueviolet',
          ],
          description: 'Badge background color',
        },
        {
          name: 'style',
          type: 'enum',
          required: false,
          default: 'flat',
          enumValues: ['plastic', 'flat', 'flat-square', 'for-the-badge', 'social'],
          description: 'Visual badge style',
        },
      ],
    };
  }

  capabilities(): ProviderCapability[] {
    return ['DYNAMIC_IMAGE', 'BADGE'];
  }

  validateConfiguration(parameters: Record<string, unknown>): Record<string, unknown> {
    return ProviderUrlBuilder.validateParameters(
      'shields-badge',
      this.metadata().configurationSchema,
      parameters,
    );
  }

  resolve(request: ProviderRequest): ProviderResult {
    const validated = this.validateConfiguration(request.parameters) as Record<string, string>;
    const url = ProviderUrlBuilder.buildUrl('shields-badge', this.baseUrl, validated);
    ProviderUrlBuilder.assertUrlSafety('shields-badge', url, this.allowedHosts);

    return {
      providerKey: 'shields-badge',
      version: '1.0.0',
      status: 'SUCCESS',
      contentType: 'IMAGE_URL',
      url,
      metadata: {
        host: 'img.shields.io',
      },
      generatedAt: new Date().toISOString(),
    };
  }

  health(): ProviderHealth {
    return {
      providerKey: 'shields-badge',
      status: 'ENABLED',
      lastCheckedAt: new Date().toISOString(),
      lastSuccessAt: new Date().toISOString(),
      failureCount: 0,
      latencyMs: 25,
    };
  }
}

// ---------------------------------------------------------------------------
// 6. External Visitor Counter Provider (visitor-badge)
// ---------------------------------------------------------------------------

@Injectable()
export class ExternalVisitorCounterProvider implements DynamicProvider {
  private readonly baseUrl = 'https://visitor-badge.laobi.workers.dev/?page={page}&color={color}';
  private readonly allowedHosts = ['visitor-badge.laobi.workers.dev'];

  metadata(): ProviderMetadata {
    return {
      providerKey: 'visitor-counter',
      name: 'Profile Visitor Counter Badge',
      description: 'Dynamic profile hit/visitor counter badge.',
      category: 'VISITOR_COUNTER',
      version: '1.0.0',
      enabled: true,
      status: 'ENABLED',
      isSystem: true,
      capabilities: ['DYNAMIC_IMAGE'],
      supportedComponents: ['visitor-counter'],
      documentationUrl: 'https://visitor-badge.laobi.workers.dev',
      configurationSchema: [
        {
          name: 'page',
          type: 'string',
          required: true,
          maxLength: 128,
          pattern: '^[A-Za-z0-9._/-]+$',
          description: 'Unique page identifier',
        },
        {
          name: 'color',
          type: 'enum',
          required: false,
          default: 'blue',
          enumValues: ['blue', 'green', 'orange', 'red', 'grey'],
          description: 'Badge color',
        },
      ],
    };
  }

  capabilities(): ProviderCapability[] {
    return ['DYNAMIC_IMAGE'];
  }

  validateConfiguration(parameters: Record<string, unknown>): Record<string, unknown> {
    return ProviderUrlBuilder.validateParameters(
      'visitor-counter',
      this.metadata().configurationSchema,
      parameters,
    );
  }

  resolve(request: ProviderRequest): ProviderResult {
    const validated = this.validateConfiguration(request.parameters) as Record<string, string>;
    const url = ProviderUrlBuilder.buildUrl('visitor-counter', this.baseUrl, validated);
    ProviderUrlBuilder.assertUrlSafety('visitor-counter', url, this.allowedHosts);

    return {
      providerKey: 'visitor-counter',
      version: '1.0.0',
      status: 'SUCCESS',
      contentType: 'IMAGE_URL',
      url,
      metadata: {
        host: 'visitor-badge.laobi.workers.dev',
      },
      generatedAt: new Date().toISOString(),
    };
  }

  health(): ProviderHealth {
    return {
      providerKey: 'visitor-counter',
      status: 'ENABLED',
      lastCheckedAt: new Date().toISOString(),
      lastSuccessAt: new Date().toISOString(),
      failureCount: 0,
      latencyMs: 30,
    };
  }
}

// ---------------------------------------------------------------------------
// 7. External Custom Image Provider (Direct HTTPS with strict SSRF defense)
// ---------------------------------------------------------------------------

@Injectable()
export class ExternalCustomImageProvider implements DynamicProvider {
  metadata(): ProviderMetadata {
    return {
      providerKey: 'custom-image',
      name: 'Custom HTTPS Image',
      description: 'Validated direct external HTTPS image URL.',
      category: 'CUSTOM_IMAGE',
      version: '1.0.0',
      enabled: true,
      status: 'ENABLED',
      isSystem: true,
      capabilities: ['DYNAMIC_IMAGE'],
      supportedComponents: ['hero', 'about', 'social-links'],
      configurationSchema: [
        {
          name: 'url',
          type: 'string',
          required: true,
          maxLength: 2048,
          pattern: '^https://.+',
          description: 'Direct HTTPS image URL',
        },
      ],
    };
  }

  capabilities(): ProviderCapability[] {
    return ['DYNAMIC_IMAGE'];
  }

  validateConfiguration(parameters: Record<string, unknown>): Record<string, unknown> {
    return ProviderUrlBuilder.validateParameters(
      'custom-image',
      this.metadata().configurationSchema,
      parameters,
    );
  }

  resolve(request: ProviderRequest): ProviderResult {
    const validated = this.validateConfiguration(request.parameters) as Record<string, string>;
    const url = validated['url'];
    // Validates scheme is https, host is not private/loopback/cloud metadata/internal
    ProviderUrlBuilder.assertUrlSafety('custom-image', url, [], true);

    return {
      providerKey: 'custom-image',
      version: '1.0.0',
      status: 'SUCCESS',
      contentType: 'IMAGE_URL',
      url,
      metadata: {
        isCustom: true,
      },
      generatedAt: new Date().toISOString(),
    };
  }

  health(): ProviderHealth {
    return {
      providerKey: 'custom-image',
      status: 'ENABLED',
      lastCheckedAt: new Date().toISOString(),
      lastSuccessAt: new Date().toISOString(),
      failureCount: 0,
      latencyMs: 1,
    };
  }
}
